name: Terraform CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    env:
      TF_VAR_ami_id: ${{ vars.AMI_ID }}
      TF_VAR_target_cpu_utilization: "50"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v40

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::875521761198:role/highly-available-aws-github-actions-role
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan